apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
        - name: bank-app
          image: docker.io/aleksei/bank-bank:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service
spec:
  selector:
    app: bank
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer