apiVersion: v1
kind: Service
metadata:
  name: {{ include "bank_chart.fullname" . }}
  labels:
    app: {{ .Values.service.serviceLabel }}
    job: {{ .Values.service.jobName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bank_chart.selectorLabels" . | nindent 4 }}
